[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/api/pi/approve"
to = "/.netlify/functions/approve"
status = 200
force = true

[[redirects]]
from = "/api/pi/complete"
to = "/.netlify/functions/complete"
status = 200
force = true

[[redirects]]
from = "/api/pi/balance"
to = "/.netlify/functions/balance"
status = 200
force = true

[[redirects]]
from = "/api/pi/withdraw"
to = "/.netlify/functions/withdraw"
status = 200
force = true
