# Donate Way â€” Pi TOML
# Place this file at: https://pi-links.netlify.app/.well-known/pi.toml

VERSION="2.0.0"

NETWORK_PASSPHRASE="Pi Testnet"
HORIZON_URL="https://api.testnet.minepi.com"

ACCOUNTS=[
  "GBQ3H472BMOMTFRSK5P26FBRVOE3ZFCB5F3FTGXEGOV5CN7RAB6TRPJR"
]

[DOCUMENTATION]
ORG_NAME="Donate Way"
ORG_URL="https://pi-links.netlify.app"
ORG_LOGO="https://pi-links.netlify.app/token_512.png"
ORG_DESCRIPTION="Donate Way token on Pi Testnet for donations."

[[CURRENCIES]]
code="DONATEWAY"
issuer="GBQ3H472BMOMTFRSK5P26FBRVOE3ZFCB5F3FTGXEGOV5CN7RAB6TRPJR"
display_decimals=2
name="Donate Way"
desc="Donate Way token on Pi Testnet for donations."
image="https://pi-links.netlify.app/token_512.png"
